"""Prefer compatible model-owner routes; DeepSeek arms use verified ZDR hosts."""
MODELS = [{'name': 'qwen3_8_flash',
  'id': 'qwen/qwen3.8-flash',
  'provider': 'openrouter',
  'max_transport_attempts': 1,
  'extra': {'reasoning': {'exclude': False, 'enabled': True},
            'response_format': {'type': 'json_object'}},
  'provider_routing': {'only': ['alibaba'],
                       'allow_fallbacks': False,
                       'require_parameters': True,
                       'data_collection': 'deny'},
  'omit_sampling': True,
  'require_readable_reasoning': True,
  'output_token_parameter': 'max_tokens',
  'expected_provider': 'Alibaba',
  'expected_returned_model_ids': ['qwen/qwen3.8-flash']},
 {'name': 'deepseek_v4_flash_vision_exp',
  'id': 'deepseek/deepseek-v4-flash-vision-exp',
  'provider': 'openrouter',
  'max_transport_attempts': 1,
  'extra': {'reasoning': {'exclude': False, 'effort': 'max'},
            'response_format': {'type': 'json_object'}},
  'provider_routing': {'only': ['deepinfra/fp8'],
                       'allow_fallbacks': False,
                       'require_parameters': True,
                       'data_collection': 'deny',
                       'zdr': True},
  'omit_sampling': True,
  'require_readable_reasoning': True,
  'output_token_parameter': 'max_tokens',
  'expected_provider': 'DeepInfra',
  'expected_returned_model_ids': ['deepseek/deepseek-v4-flash-vision-exp']},
 {'name': 'muse_spark_1_3',
  'id': 'meta/muse-spark-1.3',
  'provider': 'openrouter',
  'max_transport_attempts': 1,
  'extra': {'reasoning': {'exclude': False, 'effort': 'max'},
            'response_format': {'type': 'json_object'}},
  'provider_routing': {'only': ['meta'],
                       'allow_fallbacks': False,
                       'require_parameters': True,
                       'data_collection': 'deny'},
  'omit_sampling': True,
  'require_readable_reasoning': True,
  'output_token_parameter': 'max_tokens',
  'expected_provider': 'Meta',
  'expected_returned_model_ids': ['meta/muse-spark-1.3']},
 {'name': 'glm_5_3_flash',
  'id': 'z-ai/glm-5.3-flash',
  'provider': 'openrouter',
  'max_transport_attempts': 1,
  'extra': {'reasoning': {'exclude': False, 'effort': 'max'},
            'response_format': {'type': 'json_object'}},
  'provider_routing': {'only': ['z-ai/fp8'],
                       'allow_fallbacks': False,
                       'require_parameters': True,
                       'data_collection': 'deny',
                       'zdr': True},
  'omit_sampling': True,
  'require_readable_reasoning': True,
  'output_token_parameter': 'max_tokens',
  'expected_provider': 'Z.AI',
  'expected_returned_model_ids': ['z-ai/glm-5.3-flash']},
 {'name': 'qwen3_8_max_prime',
  'id': 'qwen/qwen3.8-max-prime',
  'provider': 'openrouter',
  'max_transport_attempts': 1,
  'extra': {'reasoning': {'exclude': False, 'effort': 'xhigh'},
            'response_format': {'type': 'json_object'}},
  'provider_routing': {'only': ['alibaba'],
                       'allow_fallbacks': False,
                       'require_parameters': True,
                       'data_collection': 'deny'},
  'omit_sampling': True,
  'require_readable_reasoning': True,
  'output_token_parameter': 'max_tokens',
  'expected_provider': 'Alibaba',
  'expected_returned_model_ids': ['qwen/qwen3.8-max-prime']},
 {'name': 'claude_sonnet_5_5',
  'id': 'anthropic/claude-sonnet-5.5',
  'provider': 'openrouter',
  'max_transport_attempts': 1,
  'extra': {'reasoning': {'exclude': False, 'effort': 'max'},
            'response_format': {'type': 'json_object'}},
  'provider_routing': {'only': ['anthropic'],
                       'allow_fallbacks': False,
                       'require_parameters': True,
                       'data_collection': 'deny'},
  'omit_sampling': True,
  'require_readable_reasoning': True,
  'output_token_parameter': 'max_tokens',
  'expected_provider': 'Anthropic',
  'expected_returned_model_ids': ['anthropic/claude-sonnet-5.5']},
 {'name': 'claude_opus_5_5',
  'id': 'anthropic/claude-opus-5.5',
  'provider': 'openrouter',
  'max_transport_attempts': 1,
  'extra': {'reasoning': {'exclude': False, 'effort': 'max'},
            'response_format': {'type': 'json_object'}},
  'provider_routing': {'only': ['anthropic'],
                       'allow_fallbacks': False,
                       'require_parameters': True,
                       'data_collection': 'deny'},
  'omit_sampling': True,
  'require_readable_reasoning': True,
  'output_token_parameter': 'max_tokens',
  'expected_provider': 'Anthropic',
  'expected_returned_model_ids': ['anthropic/claude-opus-5.5']},
 {'name': 'deepseek_v4_1_flash',
  'id': 'deepseek/deepseek-v4.1-flash',
  'provider': 'openrouter',
  'max_transport_attempts': 1,
  'extra': {'reasoning': {'exclude': False, 'effort': 'max'},
            'response_format': {'type': 'json_object'}},
  'provider_routing': {'only': ['fireworks'],
                       'allow_fallbacks': False,
                       'require_parameters': True,
                       'data_collection': 'deny',
                       'zdr': True},
  'omit_sampling': True,
  'require_readable_reasoning': True,
  'output_token_parameter': 'max_tokens',
  'expected_provider': 'Fireworks',
  'expected_returned_model_ids': ['deepseek/deepseek-v4.1-flash']},
 {'name': 'gemini_3_7_flash',
  'id': 'google/gemini-3.7-flash',
  'provider': 'openrouter',
  'max_transport_attempts': 1,
  'extra': {'reasoning': {'exclude': False, 'effort': 'high'},
            'response_format': {'type': 'json_object'}},
  'provider_routing': {'only': ['google-vertex/global'],
                       'allow_fallbacks': False,
                       'require_parameters': True,
                       'data_collection': 'deny',
                       'zdr': True},
  'omit_sampling': True,
  'require_readable_reasoning': True,
  'output_token_parameter': 'max_tokens',
  'expected_provider': 'Google',
  'expected_returned_model_ids': ['google/gemini-3.7-flash']},
 {'name': 'muse_spark_1_2',
  'id': 'meta/muse-spark-1.2',
  'provider': 'openrouter',
  'max_transport_attempts': 1,
  'extra': {'reasoning': {'exclude': False, 'effort': 'xhigh'},
            'response_format': {'type': 'json_object'}},
  'provider_routing': {'only': ['meta'],
                       'allow_fallbacks': False,
                       'require_parameters': True,
                       'data_collection': 'deny'},
  'omit_sampling': True,
  'require_readable_reasoning': True,
  'output_token_parameter': 'max_tokens',
  'expected_provider': 'Meta',
  'expected_returned_model_ids': ['meta/muse-spark-1.2']},
 {'name': 'kimi_k3',
  'id': 'moonshotai/kimi-k3',
  'provider': 'openrouter',
  'max_transport_attempts': 1,
  'extra': {'reasoning': {'exclude': False, 'effort': 'max'},
            'response_format': {'type': 'json_object'}},
  'provider_routing': {'only': ['moonshotai/mxfp4'],
                       'allow_fallbacks': False,
                       'require_parameters': True,
                       'data_collection': 'deny',
                       'zdr': True},
  'omit_sampling': True,
  'require_readable_reasoning': True,
  'output_token_parameter': 'max_tokens',
  'expected_provider': 'Moonshot AI',
  'expected_returned_model_ids': ['moonshotai/kimi-k3']},
 {'name': 'gpt_6_1_sol_pro',
  'id': 'openai/gpt-6.1-sol-pro',
  'provider': 'openrouter',
  'max_transport_attempts': 1,
  'extra': {'reasoning': {'exclude': False, 'effort': 'max', 'summary': 'detailed'},
            'response_format': {'type': 'json_object'}},
  'provider_routing': {'only': ['openai'],
                       'allow_fallbacks': False,
                       'require_parameters': True,
                       'data_collection': 'deny'},
  'omit_sampling': True,
  'require_readable_reasoning': True,
  'output_token_parameter': 'max_tokens',
  'expected_provider': 'OpenAI',
  'expected_returned_model_ids': ['openai/gpt-6.1-sol-pro']},
 {'name': 'gpt_6_sol',
  'id': 'openai/gpt-6-sol',
  'provider': 'openrouter',
  'max_transport_attempts': 1,
  'extra': {'reasoning': {'exclude': False, 'effort': 'max', 'summary': 'detailed'},
            'response_format': {'type': 'json_object'}},
  'provider_routing': {'only': ['openai'],
                       'allow_fallbacks': False,
                       'require_parameters': True,
                       'data_collection': 'deny'},
  'omit_sampling': True,
  'require_readable_reasoning': True,
  'output_token_parameter': 'max_tokens',
  'expected_provider': 'OpenAI',
  'expected_returned_model_ids': ['openai/gpt-6-sol']},
 {'name': 'grok_4_7',
  'id': 'x-ai/grok-4.7',
  'provider': 'openrouter',
  'max_transport_attempts': 1,
  'extra': {'reasoning': {'exclude': False, 'effort': 'xhigh'},
            'response_format': {'type': 'json_object'}},
  'provider_routing': {'only': ['xai/zdr'],
                       'allow_fallbacks': False,
                       'require_parameters': True,
                       'data_collection': 'deny',
                       'zdr': True},
  'omit_sampling': True,
  'require_readable_reasoning': True,
  'output_token_parameter': 'max_tokens',
  'expected_provider': 'xAI',
  'expected_returned_model_ids': ['x-ai/grok-4.7']},
 {'name': 'glm_5_3_flashx',
  'id': 'z-ai/glm-5.3-flashx',
  'provider': 'openrouter',
  'max_transport_attempts': 1,
  'extra': {'reasoning': {'exclude': False, 'effort': 'max'},
            'response_format': {'type': 'json_object'}},
  'provider_routing': {'only': ['z-ai/fp8'],
                       'allow_fallbacks': False,
                       'require_parameters': True,
                       'data_collection': 'deny',
                       'zdr': True},
  'omit_sampling': True,
  'require_readable_reasoning': True,
  'output_token_parameter': 'max_tokens',
  'expected_provider': 'Z.AI',
  'expected_returned_model_ids': ['z-ai/glm-5.3-flashx']}]
